neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/ChainBuilder.java
neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/Migrations.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/MigrationsTest.java

Check for the existence of dbms.showCurrentUser.

---

neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/MigrationVersion.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/ChainBuilderTest.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/DiscovererTest.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/DiscoveryServiceTest.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/MigrationVersionTest.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/MigrationsEETest.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/MigrationsTest.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/test_migrations/changeset2/V023_1_1__NichtsIstWieEsScheintNeuNeu.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/test_migrations/changeset2/V023_1__NichtsIstWieEsScheintNeu.java
neo4j-migrations-core/src/test/resources/my/awesome/migrations/V021.1.1__Die halbe Wahrheit neu neu.cypher
neo4j-migrations-core/src/test/resources/my/awesome/migrations/V021.1__Die halbe Wahrheit neu.cypher
neo4j-migrations-core/src/test/resources/my/awesome/migrations/moreStuff/V007_1_1__BondTheNameIsBondNewNew.cypher
neo4j-migrations-core/src/test/resources/my/awesome/migrations/moreStuff/V007_1__BondTheNameIsBondNew.cypher
neo4j-migrations-spring-boot-starter-parent/pom.xml
pom.xml

A partial solution for https://github.com/michael-simons/neo4j-migrations/issues/159

Enhance versioning support

---

.github/workflows/draft_release.yml
.github/workflows/release.yml
etc/changelog.tpl.md
pom.xml

Use JReleaser for creating a Git release in draft mode

Add JReleaser configuration

---

neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/Defaults.java
neo4j-migrations-spring-boot-starter-parent/neo4j-migrations-spring-boot-autoconfigure/src/main/java/ac/simons/neo4j/migrations/springframework/boot/autoconfigure/MigrationsProperties.java

chore: Make javadoc happy.

---

neo4j-migrations-cli/pom.xml
neo4j-migrations-core/pom.xml
neo4j-migrations-maven-plugin/pom.xml
neo4j-migrations-spring-boot-starter-parent/neo4j-migrations-spring-boot-autoconfigure/pom.xml
pom.xml

See: https://github.com/SonarSource/sonar-scanning-examples/tree/master/sonarqube-scanner-maven/maven-multimodule

build: Follow the Sonar manual for aggregating multi-module test-data.

---

docs/usage.adoc
neo4j-migrations-cli/pom.xml
neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/ConnectedCommand.java
neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/MigrationsCli.java
neo4j-migrations-cli/src/test/java/ac/simons/neo4j/migrations/cli/MigrationsCliTest.java

By reading passwords from the environment or from a file passwords can
be safely used and propageted in scripts and CI/CD environments.

feat: Allow safe passwords in scripts.

---

docs/download.adoc
docs/usage.adoc
neo4j-migrations-quarkus-parent/deployment/src/test/java/ac/simons/neo4j/migrations/quarkus/WithDifferentLocationIT.java
neo4j-migrations-quarkus-parent/deployment/src/test/java/ac/simons/neo4j/migrations/quarkus/WithMigrationsDisabledIT.java
neo4j-migrations-quarkus-parent/integration-tests/src/main/resources/application.properties
neo4j-migrations-quarkus-parent/runtime/src/main/java/ac/simons/neo4j/migrations/quarkus/runtime/MigrationsProperties.java
neo4j-migrations-quarkus-parent/runtime/src/main/resources/META-INF/quarkus-extension.yaml

Use the same namespace for Quarkus as for Boot.

---

.github/workflows/release.yml

build: Use official GraalVM action for releasing.

---

neo4j-migrations-quarkus-parent/deployment/pom.xml
neo4j-migrations-quarkus-parent/deployment/src/main/java/ac/simons/neo4j/migrations/quarkus/deployment/MigrationsProcessor.java
neo4j-migrations-quarkus-parent/deployment/src/test/java/ac/simons/neo4j/migrations/quarkus/WithDefaultLocationIT.java
neo4j-migrations-quarkus-parent/deployment/src/test/java/ac/simons/neo4j/migrations/quarkus/WithDifferentLocationIT.java
neo4j-migrations-quarkus-parent/deployment/src/test/java/ac/simons/neo4j/migrations/quarkus/WithMigrationsDisabledIT.java
neo4j-migrations-quarkus-parent/deployment/src/test/java/ac/simons/neo4j/migrations/quarkus/deployment/MigrationsProcessorTest.java
neo4j-migrations-quarkus-parent/integration-tests/src/main/java/ac/simons/neo4j/migrations/quarkus/it/migrations/SomeService.java
neo4j-migrations-quarkus-parent/integration-tests/src/test/java/ac/simons/neo4j/migrations/quarkus/AbstractITTestBase.java
neo4j-migrations-quarkus-parent/runtime/pom.xml
neo4j-migrations-quarkus-parent/runtime/src/main/java/ac/simons/neo4j/migrations/quarkus/runtime/StaticClasspathResourceScanner.java
neo4j-migrations-quarkus-parent/runtime/src/main/java/ac/simons/neo4j/migrations/quarkus/runtime/StaticJavaBasedMigrationDiscoverer.java
neo4j-migrations-quarkus-parent/runtime/src/test/java/ac/simons/neo4j/migrations/quarkus/runtime/StaticClasspathResourceScannerTest.java
pom.xml

While the original version already abstracted the ClassGraph API away, this evolution uses Quarkus' native mechanism to discover classes and resources.

refactor: Use Quarkus' built-in class indes and classpath resource utils.

---

neo4j-migrations-quarkus-parent/runtime/pom.xml
neo4j-migrations-quarkus-parent/runtime/src/test/java/ac/simons/neo4j/migrations/quarkus/runtime/StaticClasspathResourceScannerTest.java
neo4j-migrations-quarkus-parent/runtime/src/test/java/ac/simons/neo4j/migrations/quarkus/runtime/protocol/resource/Handler.java

I hate the red quality gate and I figure it's easier to add a test than
figuring out how to exclude that line from Sonar. But: Digging into how
to add a custom URL handler makes me reconsider my lifechoices once again.

fix: Add a test for the GraalVM 22.1 fix.

---

bin/test_native_cli.java
docs/usage.adoc
extensions/neo4j-migrations-formats-adoc/src/test/java/ac/simons/neo4j/migrations/formats/adoc/AsciiDoctorBasedMigrationProviderIT.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/ChainBuilderIT.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/MigrationsEEIT.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/MigrationsIT.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/PreconditionsIT.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/TestBase.java
neo4j-migrations-examples/neo4j-migrations-examples-sb/src/test/java/org/neo4j/migrations/examples/sb/ApplicationIT.java
neo4j-migrations-quarkus-parent/deployment/src/test/java/ac/simons/neo4j/migrations/quarkus/Neo4jTestResource.java
neo4j-migrations-spring-boot-starter-parent/neo4j-migrations-spring-boot-autoconfigure/src/test/java/ac/simons/neo4j/migrations/springframework/boot/autoconfigure/MigrationsAutoConfigurationIT.java
pom.xml

build: Use a system property to configure a central Neo4j image to be used as default in integration tests.

---

neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/internal/Neo4jVersionComparator.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/internal/Neo4jVersionComparatorTest.java

fix: Strip leading product specific information from version string.

---

docs/concepts.adoc
neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/CypherBasedMigration.java
neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/DefaultCypherResource.java
neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/DiscoveryService.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/ChangedPreconditionsIT.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/DefaultCypherResourceTest.java
neo4j-migrations-core/src/test/resources/parsing/V01__with_assumption.cypher
neo4j-migrations-core/src/test/resources/parsing/V01__with_random_comments.cypher
neo4j-migrations-core/src/test/resources/parsing/V01__without_assumption.cypher
neo4j-migrations-core/src/test/resources/preconditions3/new/V02__Applied_to_both.cypher
neo4j-migrations-core/src/test/resources/preconditions3/new/compat/V01__This_is_going_to_be_changed.cypher
neo4j-migrations-core/src/test/resources/preconditions3/new/current/V01__This_is_going_to_be_changed.cypher
neo4j-migrations-core/src/test/resources/preconditions3/old/V01__This_is_going_to_be_changed.cypher
neo4j-migrations-core/src/test/resources/preconditions3/old/V02__Applied_to_both.cypher

feat: Allow adding preconditions to migrations after they have been applied.

---

README.adoc

Happened to see it while reading the docs

Fix tiny typo

---

neo4j-migrations-quarkus-parent/deployment/src/main/resources/dev-templates/migrations.html

Use fluid layout for the main table.

fix: Adjust layout to commonly used one.

---

neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/internal/Neo4jVersionComparator.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/internal/Neo4jVersionComparatorTest.java

fix: Handle additional Neo4j server agent strings.

---

docs/usage.adoc
neo4j-migrations-cli/pom.xml
neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/CommonEnvVarDefaultProvider.java
neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/MigrationsCli.java
neo4j-migrations-cli/src/test/java/ac/simons/neo4j/migrations/cli/EnvironmentVarIT.java

This allows `NEO4J_URI`, `NEO4J_USERNAME` and `NEO4J_PASSWORD` to be
retrieved from environment variables.

feat: Support well-known Neo4j environment variables.

---

docs/concepts.adoc
neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/CatalogBasedRefactorings.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/CatalogBasedMigrationTest.java
neo4j-migrations-core/src/test/resources/catalogbased/parsing/broken-refactorings.xml

Polishing.

---

docs/appendix.adoc
docs/usage.adoc
neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/ConnectedCommand.java
neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/MigrationsCli.java
neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/RunCommand.java
neo4j-migrations-cli/src/test/java/ac/simons/neo4j/migrations/cli/ExceptionHandlingTest.java
neo4j-migrations-cli/src/test/java/ac/simons/neo4j/migrations/cli/RunCommandTest.java
neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/Migrations.java
neo4j-migrations-core/src/main/resources/ac/simons/neo4j/migrations/core/messages.properties
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/MigrationsIT.java
neo4j-migrations-core/src/test/resources/manual_resources/V000__Create_graph.cypher
neo4j-migrations-core/src/test/resources/manual_resources/V000__Create_schema.cypher
neo4j-migrations-core/src/test/resources/manual_resources/V000__Invalid.extension
neo4j-migrations-core/src/test/resources/manual_resources/V000__Refactor_graph.xml
neo4j-migrations-core/src/test/resources/manual_resources/invalid_filename.cypher

feat: Add the ability to run migrations and refactorings directly without recording them.

---

neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/ConnectedCommand.java
neo4j-migrations-cli/src/test/java/ac/simons/neo4j/migrations/cli/ConnectedCommandTest.java

refactor: Include reasons in CLI log when being able to render catalog items.

---

neo4j-migrations-cli/src/test/java/ac/simons/neo4j/migrations/cli/MigrationsCliTest.java
neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/MigrationsConfig.java
neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/catalog/IndexToCypherRenderer.java
neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/catalog/Renderer.java
neo4j-migrations-quarkus-parent/deployment/src/test/java/ac/simons/neo4j/migrations/quarkus/WithDifferentLocationIT.java

refactor: More JDK 17 related polishing.

---

extensions/neo4j-migrations-annotation-processing/pom.xml
extensions/neo4j-migrations-annotation-processing/processor-api/pom.xml
extensions/neo4j-migrations-annotation-processing/processor/pom.xml
extensions/neo4j-migrations-formats-adoc/pom.xml
extensions/neo4j-migrations-formats-markdown/pom.xml
neo4j-migrations-cli/pom.xml
neo4j-migrations-core/pom.xml
neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/Neo4jVersion.java
neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/refactorings/DefaultMigrateBTreeIndexes.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/CatalogBasedMigrationIT.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/MigrationsIT.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/Neo4jImageNameSubstitutor.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/Neo4jVersionTest.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/SkipArm64IncompatibleConfiguration.java
neo4j-migrations-core/src/test/resources/ee/V01__Use_some_enterprise_features.cypher
neo4j-migrations-examples/neo4j-migrations-examples-sb-testharness/pom.xml
neo4j-migrations-examples/neo4j-migrations-examples-sb/pom.xml
neo4j-migrations-examples/pom.xml
neo4j-migrations-maven-plugin/pom.xml
neo4j-migrations-quarkus-parent/deployment/pom.xml
neo4j-migrations-quarkus-parent/integration-tests/pom.xml
neo4j-migrations-quarkus-parent/pom.xml
neo4j-migrations-quarkus-parent/runtime/pom.xml
neo4j-migrations-spring-boot-starter-parent/neo4j-migrations-spring-boot-autoconfigure/pom.xml
neo4j-migrations-spring-boot-starter-parent/neo4j-migrations-spring-boot-starter/pom.xml
neo4j-migrations-spring-boot-starter-parent/pom.xml
neo4j-migrations-test-resources/pom.xml
neo4j-migrations-test-results/pom.xml
pom.xml

Cherry picked c8e4580c1dc5f46bfe513dfc8e110b648c7b6a5c

refactor: Add full testing support for Neo4j 5.

---

.github/workflows/build.yml
neo4j-migrations-core/pom.xml
neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/Location.java
neo4j-migrations-core/src/main/resources/META-INF/native-image/eu.michael-simons.neo4j/neo4j-migrations/native-image.properties
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/LocationTest.java
neo4j-migrations-maven-plugin/src/test/java/ac/simons/neo4j/migrations/maven/AbstractConnectedMojoTest.java
neo4j-migrations-maven-plugin/src/test/resources/project-to-test/target/classes/neo4j/migrations/V010__Foo.cypher
neo4j-migrations-maven-plugin/src/test/resources/with-imp-and-schema/pom.xml

Also makes URI creation more stable (specify schema and path explicitly, handling spaces proper).
Closes #776.

fix: Ensure Maven-Plugin can deal with windows paths. (#784)

---

neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/refactorings/Merge.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/MergeIT.java

refactor: Use more JDK17 idioms.

---

neo4j-migrations-cli/src/test/java/ac/simons/neo4j/migrations/cli/MigrateBTreeIndexesCommandTest.java
neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/refactorings/Counters.java
neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/refactorings/Merge.java
neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/refactorings/MigrateBTreeIndexes.java
neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/refactorings/Normalize.java
neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/refactorings/Rename.java

Those are not meant to be changed. If custom refactorings are needed, `ac.simons.neo4j.migrations.core.refactorings.Refactoring` can be implemented.

refactor: Seal concrete refactoring interfaces

---

docs/modules/ROOT/pages/usage.adoc
neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/MigrationsCli.java
neo4j-migrations-cli/src/test/java/ac/simons/neo4j/migrations/cli/MigrationsCliTest.java
neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/IterableMigrations.java
neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/Migrations.java
neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/MigrationsConfig.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/IterableMigrationsTest.java
neo4j-migrations-quarkus-parent/runtime/src/main/java/ac/simons/neo4j/migrations/quarkus/runtime/MigrationsProperties.java
neo4j-migrations-quarkus-parent/runtime/src/main/java/ac/simons/neo4j/migrations/quarkus/runtime/MigrationsRecorder.java
neo4j-migrations-quarkus-parent/runtime/src/test/java/ac/simons/neo4j/migrations/quarkus/runtime/MigrationsRecorderTest.java
neo4j-migrations-spring-boot-starter-parent/neo4j-migrations-spring-boot-autoconfigure/src/main/java/ac/simons/neo4j/migrations/springframework/boot/autoconfigure/MigrationsAutoConfiguration.java
neo4j-migrations-spring-boot-starter-parent/neo4j-migrations-spring-boot-autoconfigure/src/main/java/ac/simons/neo4j/migrations/springframework/boot/autoconfigure/MigrationsProperties.java
neo4j-migrations-spring-boot-starter-parent/neo4j-migrations-spring-boot-autoconfigure/src/test/java/ac/simons/neo4j/migrations/springframework/boot/autoconfigure/MigrationsAutoConfigurationTest.java

feat: Add configurable delay.

---

neo4j-migrations-cli/pom.xml
neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/MigrationsCli.java
neo4j-migrations-cli/src/test/java/ac/simons/neo4j/migrations/cli/MigrationsCliTest.java

feat: Support `bearer` auth in CLI.

---

extensions/neo4j-migrations-annotation-processing/catalog/pom.xml
extensions/neo4j-migrations-annotation-processing/pom.xml
extensions/neo4j-migrations-annotation-processing/processor-api/pom.xml
extensions/neo4j-migrations-annotation-processing/processor/pom.xml
extensions/neo4j-migrations-formats-adoc/pom.xml
extensions/neo4j-migrations-formats-csv/pom.xml
extensions/neo4j-migrations-formats-markdown/pom.xml
neo4j-migrations-bom/pom.xml
neo4j-migrations-cli/pom.xml
neo4j-migrations-core/pom.xml
neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/Migrations.java
neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/MigrationsIT.java
neo4j-migrations-examples/neo4j-migrations-cluster-tests/pom.xml
neo4j-migrations-examples/neo4j-migrations-examples-sb-testharness/pom.xml
neo4j-migrations-examples/neo4j-migrations-examples-sb/pom.xml
neo4j-migrations-examples/pom.xml
neo4j-migrations-maven-plugin/pom.xml
neo4j-migrations-quarkus-parent/deployment/pom.xml
neo4j-migrations-quarkus-parent/integration-tests/pom.xml
neo4j-migrations-quarkus-parent/pom.xml
neo4j-migrations-quarkus-parent/runtime/pom.xml
neo4j-migrations-spring-boot-starter-parent/neo4j-migrations-spring-boot-autoconfigure/pom.xml
neo4j-migrations-spring-boot-starter-parent/neo4j-migrations-spring-boot-starter/pom.xml
neo4j-migrations-spring-boot-starter-parent/pom.xml
neo4j-migrations-test-resources/pom.xml
neo4j-migrations-test-resources/src/main/resources/softvalidations/V01__Whatever.cypher
neo4j-migrations-test-results/pom.xml
pom.xml

feat: Add overloads to `validate` and `info` allowing to skip the lock mechanism.
