neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/Discoverer.java, pom.xml
This removes the need for the workaround introduced with 829bb2ab2ad93d49fbba3f78a52af44a52616311.
=> Bump classgraph from 4.8.84 to 4.8.85

README.adoc
Description says `.cypher` while example says `.sql` as suffix
=> make the example fit explanations

neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/MigrationsLock.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/MigrationsLockTest.java
A `Neo4jException` is thrown with the code `Neo.ClientError.Schema.ConstraintAlreadyExists` when a constraint already exists that is not only equivalent but has a name.
The same scenario might happen in an upgrade from 4.3 to 4.4. at least, as there the mechanism that decides which constraints are equivalent seems to have changed.
Thanks to @ali-ince for reporting this and help me fixing it.
=> fix: Also catch `Neo.ClientError.Schema.ConstraintAlreadyExists` while locking.

neo4j-migrations-cli/pom.xml, neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/ManifestVersionProvider.java, neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/MigrationsCli.java, neo4j-migrations-cli/src/test/java/ac/simons/neo4j/migrations/cli/ManifestVersionProviderTest.java, neo4j-migrations-cli/src/test/java/ac/simons/neo4j/migrations/cli/MigrationsCliTest.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/Migrations.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/ProductionVersion.java, neo4j-migrations-core/src/main/resources/META-INF/native-image/eu.michael-simons.neo4j/neo4j-migrations/resources-config.json, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/ProductionVersionTest.java, neo4j-migrations-core/src/test/resources/META-INF/MANIFEST.MF, neo4j-migrations-maven-plugin/src/main/java/ac/simons/neo4j/migrations/maven/AbstractConnectedMojo.java, neo4j-migrations-maven-plugin/src/test/java/ac/simons/neo4j/migrations/maven/AbstractConnectedMojoTest.java
This fixes the "unknown version" when running CLI in native mode.
Also adds the user agent when run as Maven plugin.
=> fix: Add MANIFEST.MF to native bundle and provide a central way to retrieve the product version.

neo4j-migrations-cli/pom.xml, neo4j-migrations-core/pom.xml, neo4j-migrations-examples/neo4j-migrations-examples-sb-testharness/pom.xml, neo4j-migrations-examples/neo4j-migrations-examples-sb/pom.xml, neo4j-migrations-examples/pom.xml, neo4j-migrations-maven-plugin/pom.xml, neo4j-migrations-quarkus-parent/deployment/pom.xml, neo4j-migrations-quarkus-parent/integration-tests/pom.xml, neo4j-migrations-quarkus-parent/pom.xml, neo4j-migrations-quarkus-parent/runtime/pom.xml, neo4j-migrations-spring-boot-starter-parent/neo4j-migrations-spring-boot-autoconfigure/pom.xml, neo4j-migrations-spring-boot-starter-parent/neo4j-migrations-spring-boot-autoconfigure/src/main/java/ac/simons/neo4j/migrations/springframework/boot/autoconfigure/MigrationsAutoConfiguration.java, neo4j-migrations-spring-boot-starter-parent/neo4j-migrations-spring-boot-autoconfigure/src/test/java/ac/simons/neo4j/migrations/springframework/boot/autoconfigure/MigrationsAutoConfigurationTest.java, neo4j-migrations-spring-boot-starter-parent/neo4j-migrations-spring-boot-starter/pom.xml, neo4j-migrations-spring-boot-starter-parent/pom.xml, neo4j-migrations-test-resources/pom.xml, neo4j-migrations-test-results/pom.xml, pom.xml
This is a breaking change in behavior and aligns the behavior of the Spring Boot starter with the Quarkus extension: Disabling migrations will just disable migrations on startup but still provide a `Migrations` bean with the given configuration. This allows for calls to `info`, `validate` and the like without manually recreating the configuration.
This closes #342.
=> feat: Allow disabling of migrations in Spring Boot without removing the `Migrations` bean.

neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/ConnectedCommand.java, neo4j-migrations-cli/src/test/java/ac/simons/neo4j/migrations/cli/ExceptionHandlingTest.java, neo4j-migrations-cli/src/test/java/ac/simons/neo4j/migrations/cli/LoggingTest.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/ChainBuilder.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/MigrationsIT.java
=> refactor: Avoid printing a full stack trace for expected exceptions in the CLI.

neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/MigrationsCli.java, neo4j-migrations-cli/src/test/java/ac/simons/neo4j/migrations/cli/MigrationsCliTest.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/Defaults.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/internal/Location.java, neo4j-migrations-spring-boot-starter-parent/neo4j-migrations-spring-boot-autoconfigure/src/main/java/ac/simons/neo4j/migrations/springframework/boot/autoconfigure/MigrationsProperties.java
When no other locations or packages are given, use `file:./neo4j/migrations` as a default to look for migrations in the CLI.
Closes #413.
=> feat: Make `file:./neo4j/migrations` the default for `--location` in the CLI.

neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/HBD.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/Migrations.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/MigrationsLock.java, neo4j-migrations-core/src/main/resources/ac/simons/neo4j/migrations/core/messages.properties, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/ConstraintsIT.java
This is somewhat a semi-helpful feature: It will reliable assure the uniqueness of (version,migrationTarget) for nodes with the label `__Neo4jMigration`, but we can’t guarantee the same for nodes with only the version (that is, nodes that will be created or have been created without a target database.
This is because composite indexes in Neo4j ignore null and therefor non-existent properties.
While as of today there is no way to create duplicate versions with neo4j-migration itself, a unique key should prevent external tempering.
All workarounds like having a secondary constraint with an indicator whether the optional property is present like this
```
CREATE CONSTRAINT unique_version___Neo4jMigration FOR (m:__Neo4jMigration) REQUIRE (m.version, m.migrationTarget) IS UNIQUE"
CREATE …
```
=> feat: Add unique constraint for migration nodes on Neo4j 4.4.

bin/test_native_cli.java, docs/usage.adoc, neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/MigrateCommand.java, neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/internal/MigrationsCliConsoleFormatter.java, neo4j-migrations-cli/src/main/resources/META-INF/native-image/eu.michael-simons.neo4j/neo4j-migrations-cli/reflection-config.json, neo4j-migrations-cli/src/main/resources/logging.properties, neo4j-migrations-cli/src/test/java/ac/simons/neo4j/migrations/cli/ExceptionHandlingTest.java, neo4j-migrations-cli/src/test/java/ac/simons/neo4j/migrations/cli/MigrateCommandTest.java, neo4j-migrations-cli/src/test/java/ac/simons/neo4j/migrations/cli/MigrationsCliTest.java
This allows for proper distinguising CLI and Migrations (core) output.
This change alone requires a minor version bump to indicate its potentially breaking nature.
=> refactor: Separate migrations and CLI logging into syserr and sysout.

neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/DefaultMigrationContext.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/Neo4jCodes.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/catalog/Index.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/DefaultMigrationContextIT.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/DefaultMigrationContextTest.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/TestBase.java, neo4j-migrations-core/src/test/resources/doublewillfail/44+/V0001__DoStuff.cypher, neo4j-migrations-core/src/test/resources/doublewillfail/older/V0001__DoStuff.cypher
It has been deprecated in 4.4 and removed in 5.0.
To run a quick smoke test against 5.0-dev, some changes in test base has
been necessary and the `RANGE` index type needed to be added.
=> fix: Check if dbms.procedures is available or not.

.github/workflows/build.yml, bin/test_native_cli.java, neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/MigrationsCli.java, neo4j-migrations-cli/src/test/java/ac/simons/neo4j/migrations/cli/MigrationsCliTest.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/Location.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/ResourceDiscoverer.java
Using the `name` of a location without the proper scheme will lead to invalid characters in the path under Windows systems.
Fixes #521.
=> fix: Use proper URIs for filesystem based locations.

neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/DefaultMigrationContext.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/DefaultMigrationContextTest.java
=> refactor: Avoid using `ServerVersion` in favor of a plain string.

neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/Migrations.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/MigrationsLock.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/MigrationsLockIT.java
See #572. In cases in which something prevented the aquisiation of a lock at all, there’s no chance it can be safely unlocked anway.
=> refactor: Avoid an unlock attempt if the lock isn’t locked.

neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/Discoverer.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/ResourceDiscoverer.java, neo4j-migrations-core/src/test/resources/my/awesome/migrations/V5001_AlsoNotAMigration.cypher
Configure `ac.simons.neo4j.migrations.core.Discoverer` to log `DEBUG` to see the messages.
Closes #672.
=> refactor: Log skipped resources if they are not dedicated Cypher callbacks.

.gitignore, bin/generate-site.sh
The manifest plugin adds the automic (but deterministic) module name in the packaging phase, not in the compile phase.
Therefor, the site plugin would fail with
```
Creating an aggregated report for both named and unnamed modules is not possible.
Ensure that every module has a module descriptor or is a jar with a MANIFEST.MF containing an Automatic-Module-Name.
```
as the core module now is on the module path by default.
=> build: Package the modules prior to site generation.

neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/ConnectedCommand.java, neo4j-migrations-cli/src/test/java/ac/simons/neo4j/migrations/cli/ConnectedCommandTest.java
=> refactor: Include reasons in CLI log when being able to render catalog items. (#723)

neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/AbstractCypherBasedMigration.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/CatalogBasedMigration.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/ChainBuilder.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/JavaBasedMigration.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/Migration.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/MigrationVersion.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/Migrations.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/MigrationsIT.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/test_migrations/changeset5/V003__Repeatable.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/test_migrations/changeset5/V004__Standard.java
This allows to mark Java based migrations to be repeatable unrelated to their version name and also makes them repeat only when their checksum changes.
This is a breaking change if you relied on the fact that Java based migrations are always repeated! If you need this, return a random checksum on each call of `getChecksum` or a different one in case you actually want the migration to be repeated.
Close #705.
=> feat: Allow programmatic control over repeatable Java based migrations.

neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/DiscoveryService.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/MigrationsIT.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/test_migrations/changeset6/V001__FirstMigration.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/test_migrations/changeset6/V001__SecondMigration.java, neo4j-migrations-test-resources/src/main/resources/duplicate/V001__Hallo.cypher, neo4j-migrations-test-resources/src/main/resources/duplicate/V001__Hello.cypher
=> fix: Manually check for duplicate versions and don’t rely on the constraint.

neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/Neo4jVersion.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/refactorings/DefaultMigrateBTreeIndexes.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/CatalogBasedMigrationIT.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/MigrationsIT.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/Neo4jImageNameSubstitutor.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/Neo4jVersionTest.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/SkipArm64IncompatibleConfiguration.java, neo4j-migrations-test-resources/src/main/resources/ee/V01__Use_some_enterprise_features.cypher
This is partially from https://github.com/michael-simons/neo4j-migrations/pull/699 which needs rebasing.
Summary: There is a 4.0 ARM version, we need to deal with the faster release pace of Neo4j 5 (it is not sustainable to add a new enum value each month) and we also want to have `LATEST` support in the image name substitutor.
=> refactor: Add full testing support for Neo4j 5.

neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/ConnectedCommand.java, neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/MigrateBTreeIndexesCommand.java, neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/MigrationsCli.java, neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/RunCommand.java, neo4j-migrations-cli/src/main/resources/logging.properties, neo4j-migrations-cli/src/test/java/ac/simons/neo4j/migrations/cli/MigrateBTreeIndexesCommandTest.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/refactorings/DefaultMigrateBTreeIndexes.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/refactorings/MigrateBTreeIndexes.java
Adds the `MigrateBTreeIndexes` refactoring as hidden but directly accesible command to the CLI.
Retrieve help about it via
```
neo4j-migrations help migrateBTreeIndexes
```
This can be used without any other refactoring or configuration. Username, password and database url are required though.
=> feat: Add `migrateBTreeIndexes` cmd to CLI.

neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/ConnectedCommand.java, neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/MigrateBTreeIndexesCommand.java, neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/MigrationsCli.java, neo4j-migrations-cli/src/main/java/ac/simons/neo4j/migrations/cli/RunCommand.java, neo4j-migrations-cli/src/main/resources/logging.properties, neo4j-migrations-cli/src/test/java/ac/simons/neo4j/migrations/cli/MigrateBTreeIndexesCommandTest.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/refactorings/DefaultMigrateBTreeIndexes.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/refactorings/MigrateBTreeIndexes.java
Adds the `MigrateBTreeIndexes` refactoring as hidden but directly
accesible command to the CLI.
Retrieve help about it via
```
neo4j-migrations help migrateBTreeIndexes
```
This can be used without any other refactoring or configuration.
Username, password and database url are required though.
=> feat: Add `migrateBTreeIndexes` cmd to CLI. (#744)

neo4j-migrations-core/pom.xml, neo4j-migrations-core/src/main/java/module-info.java, pom.xml
If a module has a proper `module-info.java` declaration we must not insert into the Jar file via `Automatic-Module-Name`, otherwise the latter will have precent and thus putting all the efforts of the module into vain.
=> fix: Remove automatic automatic-module name insertion for core module.

README.adoc
Adding a link to the high-level diagrams including module, library, dependency and others at (https://sourcespy.com/github/michaelsimonsneo4jmigrations/). Intended to simplify new developer introduction to the project.
In the spirit of transparency - I am the author of the generated diagrams. Hope you find it useful.
=> Adding project diagrams link to README.adoc

extensions/neo4j-migrations-formats-adoc/pom.xml, extensions/neo4j-migrations-formats-adoc/src/main/java/ac/simons/neo4j/migrations/formats/adoc/AsciiDoctorBasedMigrationProvider.java, extensions/neo4j-migrations-formats-markdown/pom.xml, extensions/neo4j-migrations-formats-markdown/src/main/java/ac/simons/neo4j/migrations/formats/markdown/MarkdownBasedMigrationProvider.java, neo4j-migrations-cli/pom.xml, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/CatalogBasedMigration.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/CypherBasedCallback.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/CypherBasedMigration.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/CypherResource.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/CypherResourceBasedMigrationProvider.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/DefaultCatalogBasedMigrationProvider.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/DefaultCypherResource.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/ResourceContext.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/ResourceDiscoverer.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/AddSurrogateKeyIT.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/CatalogBasedMigrationTest.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/ChainBuilderTest.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/CypherBasedCallbackTest.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/CypherResourceTest.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/DefaultCypherResourceTest.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/NormalizeIT.java, neo4j-migrations-core/src/test/java/ac/simons/neo4j/migrations/core/RenameIT.java, neo4j-migrations-examples/neo4j-migrations-examples-sb-testharness/pom.xml, neo4j-migrations-examples/neo4j-migrations-examples-sb/pom.xml, neo4j-migrations-examples/neo4j-migrations-examples-sb/src/test/java/ac/simons/neo4j/migrations/examples/sb/ApplicationIT.java, neo4j-migrations-maven-plugin/pom.xml, neo4j-migrations-test-resources/src/main/resources/sb/V025__SomeConstraints.xml, pom.xml
The `ResourceContext` now has a centralised way of getting an `InputStream` for resources and checks if it runs on a Spring Boot > 3.2.0 modern nested Jar.
The factory methods for the Cypher resources that take a raw URL have been deprecated and will be removed in 3.x.
All other factory methods of resources have been internal anyway.
Fixes #1248.
=> fix: Check for `!/BOOT-IN/` vs `/!BOOT-INF/`at all relevant places of resource loading.

neo4j-migrations-quarkus-parent/deployment/src/main/java/ac/simons/neo4j/migrations/quarkus/deployment/MigrationsDevConsoleProcessor.java, neo4j-migrations-quarkus-parent/deployment/src/main/java/ac/simons/neo4j/migrations/quarkus/deployment/MigrationsProcessor.java, neo4j-migrations-quarkus-parent/integration-tests/src/main/java/ac/simons/neo4j/migrations/quarkus/it/MigrationsResource.java, neo4j-migrations-quarkus-parent/runtime/src/main/java/ac/simons/neo4j/migrations/quarkus/runtime/MigrationsBuildTimeProperties.java, neo4j-migrations-quarkus-parent/runtime/src/main/java/ac/simons/neo4j/migrations/quarkus/runtime/MigrationsConfigCustomizer.java, neo4j-migrations-quarkus-parent/runtime/src/main/java/ac/simons/neo4j/migrations/quarkus/runtime/MigrationsProperties.java, neo4j-migrations-quarkus-parent/runtime/src/main/java/ac/simons/neo4j/migrations/quarkus/runtime/MigrationsRecorder.java, neo4j-migrations-quarkus-parent/runtime/src/main/resources/META-INF/services/io.smallrye.config.SmallRyeConfigBuilderCustomizer, neo4j-migrations-quarkus-parent/runtime/src/test/java/ac/simons/neo4j/migrations/quarkus/runtime/MigrationsRecorderTest.java, pom.xml
Hello @radcortez
I hope you have time to have a look again.
I cannot find for the life of it the different in the 3rd extension now to the 2nd I migrated.
If you run the tests on this branch
```
./mvnw -DskipCoreTests -pl neo4j-migrations-quarkus-parent/runtime -pl neo4j-migrations-quarkus-parent/deployment -pl neo4j-migrations-quarkus-parent/integration-tests -am -Dcheckstyle.skip clean verify
```
like this, `BlahTest` fails with 
```
[ERROR] ac.simons.neo4j.migrations.quarkus.test.BlahTest -- Time elapsed: 2.429 s <<< ERROR!
java.lang.ExceptionInInitializerError
at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:534)
at java.base/java.lang.Class.forName(Class.java:513)
at …
```
=> Quarkus config mapping migration

neo4j-migrations-cli/pom.xml
`-march=native` can improve performance but will add a hard requirement for every CPU extension present on your CPU. This can cause issues with older CPUs or CPUs from different vendors (AMD vs Intel).
`-march=compatibility` will ensure the best compatibility with a potential performance penalty. In my experience this is not usually noticable in applications like neo4j-migrations.
If performance is a concern then another option would be to remove the flag and trust the defaults of GraalVM, which according to their docs are: `x86-64-v3 on AMD64 and armv8-a on AArch64`
=> build: Switch GraalVM `-march` flag from `native` to `compatibility`

neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/DefaultMigrationContext.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/DefaultRefactoringContext.java, neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/refactorings/DefaultMigrateBTreeIndexes.java
Signed-off-by: Michael Simons <michael@simons.ac>
=> refactor: Restrict the output of `dbms.components()` to `'Neo4j Kernel'`.
